export const ANALYSIS = {
  windowSample: {
    editDistance: `The Barcode Diagram shows a steady decrease in noise as the threshold grows.  At the end, it seems that a few features persist.  Since these complexes are all of dimension 0, that would suggest that the underlying complex has more than one component (it is disconnected).\nThe histogram supports this suspicion, as most of the stanzas are only a short distance apart.  When we compare the histogram with that of the weighted sample, the shape does not change very much.  Perhaps this suggests that the sampling techniques do not alter under this metric.\nFinally, the matrix shows several dark "L" shapes, which indicates stanzas that differ substantially from the others.  This could help identify what the disconnected components in the underlying complex.`,
    jaccardDistance: `Unfortunately, this dataset was too large to render, so I did not do any analysis on it.`,
    syllableDistance: `While the shape of this Barcode diagram is similar to that of the Levenshtein metric's, it differs substantially.  Notice the stepped lifespans of the features.\nThe histogram shows that more than half of the stanzas are less than distance 4 apart, suggesting a large cluster.  The Barcode hinted at one, maybe two disconnected components, and the histogram supports this.\nThe general shape of these does not change much under different sampling techniques, however the error thresholds change significantly.  Notice that the error range in the weighted sample is twice that of the window sample, suggesting a difference between the samples. While topological features were preserved, a statistical comparison might shed some more light on the differences.`,
  },
  weightedSample: {
    editDistance: `The Barcode, histogram, and matrix are not much different from that of the window sample.  This gives evidence that under this metric, sampling technique does not matter, and either way of sampling is truthful to the underlying complex.`,
    jaccardDistance: `These graphs show something we haven't seen before.  The Barcode diagram looks unintelligible, with every feature being persistent.  While this seems nonsensical, the histogram and matrix show us why this might be the case: the stanzas are simply very far apart from one another in this metric.\nThis suggests that two stanzas generally don't contain the same words, which is reasonable.  This might inspire a more comprehensive analysis of the words used in the poem.  One would have to use more sophisticated methods in NLP, but this seems like a decent start.`,
    syllableDistance: `This differs significantly from the windowed sample.  The difference is most visible in the matrix, where we see one very dark line, compared to a rather evenly-distributed matrix in the window sample.  This indicates that one stanza in the sample is much different than the others.\nTo investigate further, one could take a different sample or a larger sample, or even take a sample of the poem without that stanza.  This stanza may very well be an outlier, which is worth looking into.`,
  },
};
